### ISSUE TITLE
customize readme

### ISSUE THREAD

**Issue by cjwilburn** [whlgbtqtech/evictionand-jekyll#9]
move from the default readme file to one specific to the project and make a documentation directory.

**Comment by preeti98** [comment]
Could you please elaborate on what you exactly need? Thanks in advance!

**Comment by cjwilburn** [comment]
Sure @preeti98 !

You'd be doing the following:
* creating top-level `docs` directory
* moving the current `README.md` to `docs/jekyll-readme.md`
* creating a new `README.md` with a link to the Jekyll readme and the with the following H2s and placeholder text (a few lines of `lorem ipsum` will suffice)
1. Title of Project (Evictionand) 
2. How To Install
3. FAQs

**Comment by nicolas-franco** [comment]
Hi! It's indeed a good first issue, in the third section. part 2. How to install and 3. FAQs, you will provide the text for this kind of readme or we have to?

**Comment by cjwilburn** [comment]
Placeholder text (like `lorem ipsum`) is fine for now.
